/*******************************************************************************
 
* Copyright Regione Piemonte - 2024
 
* SPDX-License-Identifier: EUPL-1.2
 
******************************************************************************/
package it.csi.buonores.buonoressrv.integration.notificatore.enumerator;

public enum NotificatoreEventCode {
	MSG_SUBJECT_INVIO("MSG_SUBJECT", "Avviso di invio della","Invio della"),
	MSG_SUBJECT_RETTIFICA("MSG_SUBJECT", "Avviso di rettifica della","Rettifica della"),
	MSG_SUBJECT_BO_RETTIFICA("MSG_SUBJECT", "Avviso richiesta di rettifica della","Richiesta di rettifica della"),
	MSG_SUBJECT_BO_AMMESSA_RISERVA_CONDIZIONATA("MSG_SUBJECT", "Avviso di assegnazione condizionata della","Assegnazione condizionata della"),
	MSG_SUBJECT_BO_DINIEGO("MSG_SUBJECT", "Avviso di diniego della","Diniego della"),
	MSG_SUBJECT_BO_PERFEZIONATA_IN_PAGAMENTO("MSG_SUBJECT", "Avviso di ammissibilità della ","Ammissibilità della"),
	MSG_SUBJECT_PERFEZIONATA_IN_PAGAMENTO("MSG_SUBJECT", "Avviso di invio perfezionamento della","Invio in perfezionamento della"),
	MSG_BODY_EMAIL_INVIO("MSG_BODY_EMAIL_INVIO","",""),
	MSG_BODY_PUSH_INVIO("MSG_BODY_PUSH_INVIO", "",""),
	MSG_BODY_EMAIL_INVIO_DESTINATARIO("MSG_BODY_EMAIL_INVIO_DESTINATARIO", "",""),
	MSG_BODY_EMAIL_RETTIFICA("MSG_BODY_EMAIL_RETTIFICA","",""),
	MSG_BODY_PUSH_RETTIFICA("MSG_BODY_PUSH_RETTIFICA","",""),
	MSG_BODY_EMAIL_BO_AMMESSA_RISERVA_CONTRATTO("MSG_BODY_EMAIL_BO_AMMESSA_RISERVA_CONTRATTO","",""),
	MSG_BODY_PUSH_BO_AMMESSA_RISERVA_CONTRATTO("MSG_BODY_PUSH_BO_AMMESSA_RISERVA_CONTRATTO", "",""),
	MSG_BODY_EMAIL_BO_AMMESSA_RISERVA_INCOMPATIBILITA("MSG_BODY_EMAIL_BO_AMMESSA_RISERVA_INCOMPATIBILITA","",""),
	MSG_BODY_PUSH_BO_AMMESSA_RISERVA_INCOMPATIBILITA("MSG_BODY_PUSH_BO_AMMESSA_RISERVA_INCOMPATIBILITA", "",""),
	MSG_BODY_EMAIL_BO_RETTIFICA("MSG_BODY_EMAIL_BO_RETTIFICA","",""),
	MSG_BODY_PUSH_BO_RETTIFICA("MSG_BODY_PUSH_BO_RETTIFICA", "",""),
	MSG_BODY_MAIL_BO_PREAVVISO_DINIEGO_IN_PAGAMENTO("MSG_BODY_MAIL_BO_PREAVVISO_DINIEGO_IN_PAGAMENTO","",""),
	MSG_BODY_PUSH_BO_PREAVVISO_DINIEGO_IN_PAGAMENTO("MSG_BODY_PUSH_BO_PREAVVISO_DINIEGO_IN_PAGAMENTO", "",""),
	MSG_BODY_MAIL_BO_AMMESSA_RISERVA_INCOMPATIBILITA_CONTRATTO("MSG_BODY_MAIL_BO_AMMESSA_RISERVA_INCOMPATIBILITA_CONTRATTO","",""),
	MSG_BODY_PUSH_BO_AMMESSA_RISERVA_INCOMPATIBILITA_CONTRATTO("MSG_BODY_PUSH_BO_AMMESSA_RISERVA_INCOMPATIBILITA_CONTRATTO","",""),
	MSG_BODY_EMAIL_BO_DINIEGO_DOPO_PREAVVISO("MSG_BODY_EMAIL_BO_DINIEGO_DOPO_PREAVVISO","",""),
	MSG_BODY_PUSH_BO_DINIEGO_DOPO_PREAVVISO("MSG_BODY_PUSH_BO_DINIEGO_DOPO_PREAVVISO","",""),
	MSG_BODY_EMAIL_BO_DINIEGO_CON_CONTRODEDUZIONI("MSG_BODY_EMAIL_BO_DINIEGO_CON_CONTRODEDUZIONI","",""),
	MSG_BODY_PUSH_BO_DINIEGO_CON_CONTRODEDUZIONI("MSG_BODY_PUSH_BO_DINIEGO_CON_CONTRODEDUZIONI","",""),
	MSG_BODY_MAIL_BO_PERFEZIONATA_IN_PAGAMENTO("MSG_BODY_MAIL_BO_PERFEZIONATA_IN_PAGAMENTO","",""),
	MSG_BODY_PUSH_BO_PERFEZIONATA_IN_PAGAMENTO("MSG_BODY_PUSH_BO_PERFEZIONATA_IN_PAGAMENTO","",""),
	URL_BUONO_SOCIALE("URL_BUONO_SOCIALE","",""),
	MSG_SUBJECT_BO_PREAVVISO_DINIEGO("MSG_SUBJECT", "Preavviso di diniego della","Preavviso di diniego della"),
	MSG_BODY_EMAIL_BO_PREAVVISO_DINIEGO_NON_AMMISSIBILITA("MSG_BODY_EMAIL_BO_PREAVVISO_DINIEGO_NON_AMMISSIBILITA","",""),
	MSG_BODY_PUSH_BO_PREAVVISO_DINIEGO_NON_AMMISSIBILITA("MSG_BODY_PUSH_BO_PREAVVISO_DINIEGO_NON_AMMISSIBILITA", "",""),
	MSG_SUBJECT_CONTRODEDOTTA_CITTADINO("MSG_SUBJECT", "Avviso di invio controdeduzioni della","Avviso di invio controdeduzioni della"),
	MSG_BODY_EMAIL_CONTRODEDOTTA_CITTADINO("MSG_BODY_EMAIL_CONTRODEDOTTA_CITTADINO","",""),
	MSG_BODY_PUSH_CONTRODEDOTTA_CITTADINO("MSG_BODY_PUSH_CONTRODEDOTTA_CITTADINO", "",""),
	MSG_SUBJECT_RINUNCIATA_CITTADINO("MSG_SUBJECT", "Avviso di rinuncia della","Avviso di rinuncia della"),
	MSG_BODY_EMAIL_RINUNCIATA_CITTADINO("MSG_BODY_EMAIL_RINUNCIATA_CITTADINO","",""),
	MSG_BODY_PUSH_RINUNCIATA_CITTADINO("MSG_BODY_PUSH_RINUNCIATA_CITTADINO", "",""),
	MSG_BODY_EMAIL_BO_DINIEGO_SENZA_PREAVVISO("MSG_BODY_EMAIL_BO_DINIEGO_SENZA_PREAVVISO","",""),
	MSG_BODY_PUSH_BO_DINIEGO_SENZA_PREAVVISO("MSG_BODY_PUSH_BO_DINIEGO_SENZA_PREAVVISO","",""),
	MSG_BODY_EMAIL_BO_DINIEGO_SCADENZA_REQUISTI("MSG_BODY_EMAIL_BO_DINIEGO_SCADENZA_REQUISTI","",""),
	MSG_BODY_PUSH_BO_DINIEGO_SCADENZA_REQUISTI("MSG_BODY_PUSH_BO_DINIEGO_SCADENZA_REQUISTI","",""),
	MSG_BODY_EMAIL_BO_DINIEGO_SCADENZA_REQUISTI_DECESSO("MSG_BODY_EMAIL_BO_DINIEGO_SCADENZA_REQUISTI_DECESSO","",""),
	MSG_BODY_EMAIL_BO_DINIEGO_SCADENZA_REQUISTI_CAMBIO_RESIDENZA("MSG_BODY_EMAIL_BO_DINIEGO_SCADENZA_REQUISTI_CAMBIO_RESIDENZA","",""),
	MSG_BODY_EMAIL_PERFEZIONATA_IN_PAGAMENTO_CITTADINO("MSG_BODY_EMAIL_PERFEZIONATA_IN_PAGAMENTO_CITTADINO","",""),
	MSG_BODY_PUSH_PERFEZIONATA_IN_PAGAMENTO_CITTADINO("MSG_BODY_PUSH_PERFEZIONATA_IN_PAGAMENTO_CITTADINO", "",""),
	MSG_BODY_EMAIL_BO_AMMESSA_FINANZIATA("MSG_BODY_EMAIL_BO_AMMESSA_FINANZIATA","",""),
	MSG_BODY_PUSH_BO_AMMESSA_FINANZIATA("MSG_BODY_PUSH_BO_AMMESSA_FINANZIATA", "",""),
	MSG_SUBJECT_BO_AMMESSA_FINANZIATA("MSG_SUBJECT","Avviso di assegnazione del buono residenzialità della","Assegnazione del buono residenzialità della"),
	MSG_BODY_EMAIL_BO_AMMESSA_NON_FINANZIATA("MSG_BODY_EMAIL_BO_AMMESSA_NON_FINANZIATA","",""),
	MSG_BODY_PUSH_BO_AMMESSA_NON_FINANZIATA("MSG_BODY_PUSH_BO_AMMESSA_NON_FINANZIATA", "",""),
	MSG_BODY_MAIL_DINIEGO_DOPO_PERFEZIONATA_IN_PAGAMENTO("MSG_BODY_MAIL_DINIEGO_DOPO_PERFEZIONATA_IN_PAGAMENTO","",""),
	MSG_BODY_PUSH_DINIEGO_DOPO_PERFEZIONATA_IN_PAGAMENTO("MSG_BODY_PUSH_DINIEGO_DOPO_PERFEZIONATA_IN_PAGAMENTO", "",""),
	MSG_BODY_MAIL_DINIEGO_DOPO_PREAVVISO_DI_DINIEGO_IN_PAGAMENTO("MSG_BODY_MAIL_DINIEGO_DOPO_PREAVVISO_DI_DINIEGO_IN_PAGAMENTO","",""),
	MSG_BODY_PUSH_DINIEGO_DOPO_PREAVVISO_DI_DINIEGO_IN_PAGAMENTO("MSG_BODY_PUSH_DINIEGO_DOPO_PREAVVISO_DI_DINIEGO_IN_PAGAMENTO", "",""),
	MSG_SUBJECT_BO_AMMESSA_NON_FINANZIATA("MSG_SUBJECT","Avviso di ammissione senza finanziamento della","Ammissione senza finanziamento della"),
    MSG_SUBJECT_REVOCA_BUONO("MSG_SUBJECT_REVOCA_BUONO", "",""),
    MSG_BODY_MAIL_REVOCA_BUONO("MSG_BODY_MAIL_REVOCA_BUONO","",""),
    MSG_SUBJECT_ISEE_RESPINTO("MSG_SUBJECT", "Misura Scelta sociale – verifica attestazioni ISEE 2024 Segnalazione anomalie","Misura Scelta sociale – verifica attestazioni ISEE 2024 Segnalazione anomalie"),
    MSG_SUBJECT_ISEE_NON_CONFORME("MSG_SUBJECT", "Misura Scelta sociale – ISEE 2024","Misura Scelta sociale – ISEE 2024"),
    MSG_BODY_PUSH_ISEE_RESPINTO("MSG_BODY_PUSH_ISEE_RESPINTO", "",""),
    MSG_BODY_PUSH_ISEE_NON_CONFORME("MSG_BODY_PUSH_ISEE_NON_CONFORME", "",""),
    MSG_BODY_EMAIL_ISEE_RESPINTO("MSG_BODY_EMAIL_ISEE_RESPINTO","",""),
    MSG_BODY_EMAIL_ISEE_NON_CONFORME("MSG_BODY_EMAIL_ISEE_NON_CONFORME","",""),
    MSG_BODY_PUSH_REVOCA_BUONO("MSG_BODY_PUSH_REVOCA_BUONO", "","");

	private final String code;
	private final String title;
	private final String title1;

	private NotificatoreEventCode(String inCode, String title, String title1) {
		this.code = inCode;
		this.title = title;
		this.title1 = title1;
	}

	public String getCode() {
		return code;
	}

	public String getTitle() {
		return title;
	}

	public String getTitle1() {
		return title1;
	}

}
